### PR TITLE
Eigen 5 Survey

### PR DESCRIPTION
**Pull request by stydxm**
Topic Description
-----------------

- stress-ng: bump REL due to eigen upgrade
    Signed-off-by: stydxm <stydxm@outlook.com>
- scantailor-advanced: bump REL due to eigen upgrade
    Signed-off-by: stydxm <stydxm@outlook.com>
- pykdl: bump REL due to eigen upgrade
    Signed-off-by: stydxm <stydxm@outlook.com>
- orocos-kdl: bump REL due to eigen upgrade
    Signed-off-by: stydxm <stydxm@outlook.com>
- openscad: update to 2021.01+git20251218
    Signed-off-by: stydxm <stydxm@outlook.com>
- krita: bump REL due to eigen upgrade
    Signed-off-by: stydxm <stydxm@outlook.com>
- kalzium: bump REL due to eigen upgrade
    Signed-off-by: stydxm <stydxm@outlook.com>
- guitarix: bump REL due to eigen upgrade
    Signed-off-by: stydxm <stydxm@outlook.com>
- jack: bump REL due to eigen upgrade
    Signed-off-by: stydxm <stydxm@outlook.com>
- gmic: bump REL due to eigen upgrade
    Signed-off-by: stydxm <stydxm@outlook.com>

... and 16 more commits

Package(s) Affected
-------------------

Security Update?
----------------

No

Build Order
-----------

```
#buildit eigen-5 eigen ceres cgal superslicer vtk eigen-3 asymptote pcl opencv cloudcompare darkradiant digikam hdf5 freecad gmic jack guitarix openbabel kalzium krita openscad orocos-kdl pykdl scantailor-advanced stress-ng
```

Test Build(s) Done
------------------

**Primary Architectures**

- [x] AMD64 `amd64`
- [x] AArch64 `arm64`
- [x] LoongArch 64-bit `loongarch64`
- [ ] LoongArch 64-bit (No SIMD) `loongarch64_nosimd`

**Secondary Architectures**

- [x] Loongson 3 `loongson3`
- [x] PowerPC 64-bit (Little Endian) `ppc64el`
- [x] RISC-V 64-bit `riscv64`

### CODE REVIEW

File: app-creativity/freecad/autobuild/prepare [hunk 1]
```diff
@@ -5,6 +5,7 @@ if ab_match_arch loongson3; then
     export CXXFLAGS="$(CXXFLAGS) -Os"
 fi
 
-# FIXME: freecad/src/Mod/ReverseEngineering/App/SurfaceTriangulation.cpp:43:10: fatal error: pcl/point_traits.h: No such file or directory
-# The PCL point_traits.h header was renamed (and deprecated) since 1.11.0 and removed in 1.15.0.
-git cherry-pick -n d9e731ca94abc14808ebeed208617116f6d5ea4a
+abinfo "Applying patches ..."
+git cherry-pick -n d9e731ca94abc14808ebeed208617116f6d5ea4a # Fix build with PCL 1.15.0
```
Comment (MingcongBai) [inline app-creativity/freecad/autobuild/prepare]: Please make these tracking - also, why pick PCL if we were to disable PCL?

File: app-devel/eigen-3/autobuild/defines [hunk 2]
```diff
@@ -1,27 +1,7 @@
...
-BUILDDEP__RETRO=""
-BUILDDEP__ARMV4="${BUILDDEP__RETRO}"
-BUILDDEP__ARMV6HF="${BUILDDEP__RETRO}"
-BUILDDEP__ARMV7HF="${BUILDDEP__RETRO}"
-BUILDDEP__I486="${BUILDDEP__RETRO}"
-BUILDDEP__LOONGSON2F="${BUILDDEP__RETRO}"
-BUILDDEP__M68K="${BUILDDEP__RETRO}"
-BUILDDEP__POWERPC="${BUILDDEP__RETRO}"
-BUILDDEP__PPC64="${BUILDDEP__RETRO}"
+PKGDEP="glibc"
```
Comment (MingcongBai) [inline app-devel/eigen-3/autobuild/defines]: Header only, there shouldn't be any dependency?

File: runtime-imaging/pcl/autobuild/prepare [hunk 3]
```diff
@@ -0,0 +1,2 @@
+abinfo "Applying patches..."
+git cherry-pick -n 2d6929bdcd98beaa28fa8ee3a105beb566f16347
```
Comment (MingcongBai) [inline runtime-imaging/pcl/autobuild/prepare:2]: Please consider making this tracking (no insistence, just a suggestion).

File: runtime-scientific/ceres/autobuild/prepare [hunk 4]
```diff
@@ -0,0 +1,5 @@
+abinfo "Applying patches..."
+# FIXME: patches for Eigen 5
+git cherry-pick -n 07651df0ad17365a2616135bb46ecd92b8e36adb
```
Comment (MingcongBai) [inline runtime-scientific/ceres/autobuild/prepare:3]: Please consider making this tracking (no insistence, just a suggestion).

File: runtime-scientific/opencv/autobuild/prepare [hunk 5]
```diff
@@ -1,3 +1,7 @@
+abinfo "Setting Build flags ..."
 export LDFLAGS=" -lcblas "
 export CXXFLAGS="${CXXFLAGS} -I/usr/include/openjpeg-$(pkgconf --modversion libopenjp2 | cut -f1-2 -d'.')"
 export CFLAGS="${CFLAGS} -I/usr/include/openjpeg-$(pkgconf --modversion libopenjp2 | cut -f1-2 -d'.')"
+
+abinfo "Applying patches ..."
+git cherry-pick -n 468de9b36740b3355f0d5cd8be2ce28b340df120
```
Comment (MingcongBai) [inline runtime-scientific/opencv/autobuild/prepare:7]: Please consider making this tracking (no insistence, just a suggestion).

**Review by MingcongBai — CHANGES_REQUESTED** [review]

**Review by MingcongBai — APPROVED** [review]
