### PR TITLE
luajit: new, 2.1.0+git20250605 loongarch64

### PR DESCRIPTION
**Pull request by FurryAcetylCoA**
Topic Description
-----------------
* luajit: new, 2.1.0+git20250605 (loongarch64)  (loongarch64)
  * Upstream show no interest in adding new arch. So this [fork](https://github.com/loongson/LuaJIT) provided by loongson is selected
  * Luajit2 upstream also don't support loongarch64 (and risc-v)
  * Some distro use luajit2 as luajit, but whether we should do that is for another topic
* bcc: enable luajit (loongarch64)
* libluv: enable luajit (loongarch64)
* love11: enable luajit (loongarch64)
* luanti: enable luajit (loongarch64)
* mpv: enable luajit (loongarch64)
* libpeas: enable luajit (loongarch64)
  * No abi change found 
* openmw: new, 0.48.0+git20240902 (loongarch64)
* sysbench: new, 1.0.20 (loongarch64)
* hexchat: enable luajit (loongarch64)
* ~texlive~: uses in-tree luajit, **not included in this topic**
* gegl-0.4: enable luajit (loongarch64)
  * No abi change found
* neovim: enable luajit (loongarch64)
  * lazy.nvim is working, finally
* ~obs-studio~: depends on luajit, **not included in this topic**
   * Blocked by #11822
* ~love07~: depends on luajit, **not included in this topic**
   * Won't build with clean tree: libraries/luasocket/libluasocket/luasocket.c:113:15: error: return type defaults to ‘int’ [-Wimplicit-int]
   * Why this specific version is kept? (See also #876)
* ~hardinfo~:  indirectly depends on luajit, **not included in this topic**
  * Requires more work to support loongarch64
*  ~aegisub~: uses in-tree luajit, **not included in this topic**
   * Builts it's own luajit, not related to this topic
   * Requires luajit build with lua 5.2 compat

Package(s) Affected
-------------------

* luajit: 2.1.0+git20250605
* bcc: 0.30.0
* libluv: 1.47.0+0
* love11: 11.5
* luanti: 5.12.0
* mpv: 0.40.0
* libpeas: 1.36.0
* openmw: 0.48.0+git20240902
* sysbench: 1.0.20
* hexchat: 2.16.1
* gegl-0.4: 0.4.62
* neovim: 0.11.3

Security Update?
----------------

No

Build Order
-----------

```
#buildit luajit libluv libpeas bcc love11 luanti mpv openmw sysbench hexchat gegl-0.4 neovim
```

Test Build(s) Done
------------------

**Primary Architectures**

- [x] AMD64 `amd64`
- [x] AArch64 `arm64`
- [x] LoongArch 64-bit `loongarch64`

**Secondary Architectures**

- [x] Loongson 3 `loongson3`
- [x] PowerPC 64-bit (Little Endian) `ppc64el`
- [x] RISC-V 64-bit `riscv64`

### CODE REVIEW

**Comment by FurryAcetylCoA** [comment]
Removed texlive from this topic. Since it uses in-tree luajit

**Comment by MingcongBai** [comment]
MIPS fails:

图片

**Comment by FurryAcetylCoA** [comment]
> MIPS fails:
> 图片

A rebuild fixed that. 
Seems like some random network related stuff. I also build it locally multiple times and can't reproduce this.

File: lang-lua/luajit/spec [hunk 1]
```diff
@@ -1,4 +1,10 @@
 VER=2.1.0b3+git20250528
 SRCS="git::commit=f9140a622a0c44a99efb391cc1c2358bc8098ab7::https://luajit.org/git/luajit.git"
-CHKSUMS="SKIP"
 CHKUPDATE="anitya::id=6444"
+# Upstream shows no interest in adding new arch
+VER__LOONGARCH64=2.1.0+git20250605
```
Comment (MingcongBai) [inline lang-lua/luajit/spec]: Please use upstream tag [v2.1.ROLLING-loongarch64-20240116](https://github.com/loongson/LuaJIT/releases/tag/v2.1.ROLLING-loongarch64-20240116), which would be transcribe as:

```
VER=2.1.ROLLING+loongarch64+20240116
```

File: lang-lua/luajit/spec [hunk 2]
```diff
@@ -1,4 +1,10 @@
...
+SRCS__LOONGARCH64="git::commit=02579d06dba72769949b0e8660c875a6d20eb6b3::https://github.com/loongson/LuaJIT.git"
+CHKUPDATE__LOONGARCH64="github::repo=loongson/LuaJIT"
```
Comment (MingcongBai) [inline lang-lua/luajit/spec:9]: Consider registering `luajit-loongson` or something similar on Anitya.

**Review by MingcongBai — CHANGES_REQUESTED** [review]

File: lang-lua/luajit/spec (hunk 1 above)
Comment (FurryAcetylCoA) [reply lang-lua/luajit/spec]: The latest tag `v2.1.ROLLING-loongarch64-20240116` was created in Jan 16, 2024. 
And it does not belong to the `v2.1-loongarch64` (default) branch. An cherry-pick(or something similar) was preformed in Jan 3, 2025. 
The latest commit in default branch was created in Jun 5, 2025.
And the branch that tag belongs to is no longer developed since 2024. So that tag is useless for packing.
Hence there is no suitable tag in this repo. So I considered this as a "Versioning Variables" in §3.1 of "AOSC OS Package Styling Manual"
 
image

File: lang-lua/luajit/spec (hunk 2 above)
Comment (FurryAcetylCoA) [reply lang-lua/luajit/spec:9]: IMHO, Anitya can't handle the "don't do release" and "don't do tag" kind of project well. (e.g. luajit itself)
And since the loongson fork also "don't do release" and "don't do tag", I'm afraid this is not an optimal solution.

**Review by MingcongBai — APPROVED** [review]
